#!/usr/bin/env bash
# Installing Nginx on Server and redirect
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo touch /var/www/html/error404.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo sed -i '27 a error_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload