#!/usr/bin/env bash
# add a custom Nginx response header.
# Installing Nginx on Server
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '11 a add_header X-Served-By $hostname always;' /etc/nginx/nginx.conf
sudo service nginx restart
sudo service nginx reload