#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
hour=0
while [ $hour -le 12 ]
do
    n=1
    while [ $n -le 59 ]
    do
        echo "$n"
        ((n++))
    done
    echo "Hour: $hour"
    ((hour++)) 
done
